# Generated by Django 3.1.7 on 2021-04-11 10:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210411_0225'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registration',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
