# Generated by Django 3.1.7 on 2021-04-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210411_0343'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registration',
            managers=[
            ],
        ),
    ]
