# Generated by Django 3.1.7 on 2021-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210411_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact_num',
            field=models.BigIntegerField(),
        ),
    ]
