# Generated by Django 3.1.7 on 2021-04-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210422_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
