# Generated by Django 3.1.7 on 2021-04-26 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=7)),
                ('date_released', models.DateField(auto_now_add=True)),
                ('card_type', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('active_id', models.ImageField(upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
