# Generated by Django 3.1.7 on 2021-04-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0005_auto_20210426_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='duration_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
