# Generated by Django 3.1.7 on 2021-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0008_auto_20210427_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_pics')),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('fuel_type', models.CharField(max_length=50)),
                ('tank_capacity', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('transmission', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='car_order',
            old_name='card_type',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='car_order',
            old_name='date_released',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='car_order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='car_order',
            name='duration_type',
        ),
        migrations.AlterField(
            model_name='car_order',
            name='active_id',
            field=models.ImageField(upload_to='customer_id'),
        ),
    ]
