# Generated by Django 3.1.7 on 2021-04-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0009_auto_20210428_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_order',
            name='model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RENTaCAR.cars'),
        ),
    ]
