# Generated by Django 3.1.7 on 2021-04-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0010_car_order_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_order',
            old_name='active_id',
            new_name='valid_id',
        ),
    ]
