# Generated by Django 3.1.7 on 2021-04-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0011_auto_20210428_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_order',
            name='model',
        ),
        migrations.AddField(
            model_name='car_order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RENTaCAR.cars'),
        ),
        migrations.AddField(
            model_name='car_order',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
