# Generated by Django 3.1.7 on 2021-05-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0012_auto_20210428_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.RemoveField(
            model_name='cars',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='power',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='seating_capacity',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='tank_capacity',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='transmission',
        ),
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='specifications',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RENTaCAR.cartype'),
        ),
    ]
