# Generated by Django 3.1.7 on 2021-05-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0013_auto_20210501_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='specifications',
            field=models.TextField(max_length=4000),
        ),
    ]
