# Generated by Django 3.1.7 on 2021-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0014_auto_20210501_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(help_text='Per Day'),
        ),
    ]
