# Generated by Django 3.1.7 on 2021-05-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0015_auto_20210501_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_order',
            name='total_price',
        ),
    ]
