# Generated by Django 3.1.7 on 2021-05-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0019_car_order_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_order',
            name='sub_total',
            field=models.IntegerField(),
        ),
    ]
