# Generated by Django 3.1.7 on 2021-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0021_remove_car_order_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car_order',
            options={'get_latest_by': 'order_date'},
        ),
        migrations.AlterField(
            model_name='car_order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
