# Generated by Django 3.1.7 on 2021-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0022_auto_20210505_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_order',
            name='status',
            field=models.CharField(choices=[('On Process', 'On Process'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], max_length=20, null=True),
        ),
    ]
