# Generated by Django 3.1.7 on 2021-05-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0023_car_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RENTaCAR.cartype'),
        ),
    ]
