# Generated by Django 3.1.7 on 2021-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0024_auto_20210509_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_order',
            name='amount_payable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car_order',
            name='status',
            field=models.CharField(choices=[('On Process', 'On Process'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='On Process', max_length=20, null=True),
        ),
    ]
