# Generated by Django 3.1.7 on 2021-05-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0025_auto_20210509_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_order',
            name='amount_payable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
