# Generated by Django 3.1.7 on 2021-05-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RENTaCAR', '0026_auto_20210509_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RENTaCAR.cartype'),
        ),
    ]
